### ISSUE TITLE
Documentation for using this

### ISSUE THREAD

**Issue by Flinner** [ShadyF/Actual-Budget-SMS-Proxy#4]
Hi!

I am about to use this amazing proxy, would you accept a pull request writeup for a guide/documentation?

**Comment by Flinner** [comment]
nvm

**Comment by ShadyF** [comment]
Hi!

I didn't know if anyone would be interested! I can write up a small guide / documentation over the weekend if that helps!

Until then, here are the main things you need to know to get this up and running:
1. Global env vars, those can be found [here](https://github.com/ShadyF/actual-budget-sms-proxy/blob/9c0ca115fc17135098c2386b5610e06436d76434/src/app.ts#L33). Example of some of their usage can also be found [here](https://github.com/ShadyF/k8s-homelab/blob/master/cluster/apps/default/actual-budget/sms-proxy/deployment.yaml)
2. You'll need to create a config file that defines the structure of the SMSes you want to parse, along with some extra details. Example of the config file (non-comprehensive, doesn't have all the fields) can be found [here](https://github.com/ShadyF/actual-budget-sms-proxy/blob/main/config.example.json)
3. You can find all the possible fields for the config file [here](https://github.com/ShadyF/actual-budget-sms-proxy/blob/9c0ca115fc17135098c2386b5610e06436d76434/src/validators.ts#L31)
4. Once the server is up and running, it will receive POST requests on the `/transactions` endpoint, along with this [request payload ](https://github.com/ShadyF/actual-budget-sms-proxy/blob/9c0ca115fc17135098c2386b5610e06436d76434/src/app.ts#L94).

Small note, the `API_KEY` env var you set needs to be the same `api_key` you send in the request payload. This is a light security measure to prevent anyone from spamming the server with fake transactions.

Also, if you're thinking about how to send SMS automatically from your phone, I found out that Tasker does a great job at that (for android phones of course). I'll probably also put a sample tasker file to illustrate how it can be done over the weekend.

Let me know if there's anything else I can help with!

**Comment by Flinner** [comment]
I appreciate this! I will try to get it running :)

I have modified the code to get a csv file from an SMS dump and imported to Actual Budget :) thx
